name: first try
favicon: null
layout_spectrum: 0.04334180522710085
typography_spectrum: 0.006796272937208414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08871360868215561
  lightness: 0.8049531111028045
  saturation: 0.8194154256489128
  rhythmicContrast: 0.34413371817208827
purpose: []
